
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "ISoapShoppingListService", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISoapShoppingListService {


    /**
     *
     * @param item
     */
    @WebMethod
    @RequestWrapper(localName = "addItem", targetNamespace = "http://soap/", className = "soap.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://soap/", className = "soap.AddItemResponse")
    @Action(input = "http://soap/ISoapShoppingListService/addItemRequest", output = "http://soap/ISoapShoppingListService/addItemResponse")
    public void addItem(
        @WebParam(name = "item", targetNamespace = "")
        ShoppingItem item);

    /**
     *
     * @param item
     */
    @WebMethod
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://soap/", className = "soap.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://soap/", className = "soap.DeleteItemResponse")
    @Action(input = "http://soap/ISoapShoppingListService/deleteItemRequest", output = "http://soap/ISoapShoppingListService/deleteItemResponse")
    public void deleteItem(
        @WebParam(name = "item", targetNamespace = "")
        ShoppingItem item);

    /**
     *
     * @return
     *     returns soap.ShoppingList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShoppingList", targetNamespace = "http://soap/", className = "soap.GetShoppingList")
    @ResponseWrapper(localName = "getShoppingListResponse", targetNamespace = "http://soap/", className = "soap.GetShoppingListResponse")
    @Action(input = "http://soap/ISoapShoppingListService/getShoppingListRequest", output = "http://soap/ISoapShoppingListService/getShoppingListResponse")
    public ShoppingList getShoppingList();

}
